### ISSUE TITLE
The bitbucket example is in a private repository

### ISSUE THREAD

**Issue by iledzka** [DannyDainton/postman-ci-pipeline-example#3]
Hello, thanks for this example, it's helpful. I tried to access the link  to the sample Bitbucket Pipeline project 
 https://bitbucket.org/ddainton/postman-ci-pipeline-example/src/master/ (from README) with my bitbucket account but it looks like it's in a private repository?

**Comment by DannyDainton** [comment]
My bad - Should be public now.
